version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt

  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Python code...
      # Add any build commands specific to your application

  post_build:
    commands:
      - echo Build completed on `date`










